version: '3.8'

services:
  # 1. Database (MySQL)
  mysql:
    image: mysql:8.0
    container_name: Capstone_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: GameDB
    ports:
      - "3306:3306" 
    command: --default-authentication-plugin=mysql_native_password

  # 2. In-Memory Data Store (Redis)
  redis:
    image: redis:alpine
    container_name: Capstone_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - redis_data:/data

  # 3. Backend API Server (ASP.NET Core)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Capstone_backend
    ports:
      - "7200:8080" # Host Port(7200) : Container Port(8080)
    depends_on:
      - mysql
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=GameDB;Uid=root;Pwd=${DB_PASSWORD};
      - Redis__ConnectionString=redis:6379 
      - ConnectionStrings__RedisConnection=redis:6379

volumes:
  redis_data: